In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [2]:
pwd

'C:\\Users\\HP\\Desktop\\Airline'

In [2]:
data = pd.read_csv("train.csv")

In [5]:
data

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,103899,94171,Female,disloyal Customer,23,Business travel,Eco,192,2,1,...,2,3,1,4,2,3,2,3,0.0,neutral or dissatisfied
103900,103900,73097,Male,Loyal Customer,49,Business travel,Business,2347,4,4,...,5,5,5,5,5,5,4,0,0.0,satisfied
103901,103901,68825,Male,disloyal Customer,30,Business travel,Business,1995,1,1,...,4,3,2,4,5,5,4,7,14.0,neutral or dissatisfied
103902,103902,54173,Female,disloyal Customer,22,Business travel,Eco,1000,1,1,...,1,4,5,1,5,4,1,0,0.0,neutral or dissatisfied
103903,103903,62567,Male,Loyal Customer,27,Business travel,Business,1723,1,3,...,1,1,1,4,4,3,1,0,0.0,neutral or dissatisfied

In [3]:
X = data.drop("satisfaction", axis=1)
y = data["satisfaction"]

In [7]:
X.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,5,4,3,4,4,5,5,25,18.0
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,1,5,3,1,4,1,1,6.0
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,5,4,3,4,4,4,5,0,0.0
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,2,5,3,1,4,2,11,9.0
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,5,3,3,4,4,3,3,3,0,0.0

In [9]:
y.head()

0    neutral or dissatisfied
1    neutral or dissatisfied
2                  satisfied
3    neutral or dissatisfied
4                  satisfied
Name: satisfaction, dtype: object

In [4]:
# Convert categorical features to numerical using LabelEncoder
label_encoder = LabelEncoder()
X_encoded = X.apply(label_encoder.fit_transform)
X_encoded.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,56192,1,0,6,1,2,358,3,4,...,5,5,4,3,3,4,5,5,25,18
1,1,3978,1,1,18,0,0,144,3,2,...,1,1,1,5,2,1,4,1,1,6
2,2,88045,0,0,19,0,0,994,2,2,...,5,5,4,3,3,4,4,5,0,0
3,3,19148,0,0,18,0,0,446,2,5,...,2,2,2,5,2,1,4,2,11,9
4,4,95443,1,0,54,0,0,124,3,3,...,5,3,3,4,3,3,3,3,0,0

In [5]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

In [8]:
Random_Forest= RandomForestClassifier()

In [9]:
Random_Forest.fit(X_train, y_train)

RandomForestClassifier()

In [11]:
y_pred1 = Random_Forest.predict(X_test)

In [13]:
accuracy1 = accuracy_score(y_test, y_pred1)

In [16]:
report1 = classification_report(y_test, y_pred1)

In [17]:
print("Accuracy:", accuracy1)
print("Classification Report:")
print(report1)

Accuracy: 0.9627544391511477
Classification Report:
                         precision    recall  f1-score   support

neutral or dissatisfied       0.95      0.98      0.97     11713
              satisfied       0.97      0.94      0.96      9068

               accuracy                           0.96     20781
              macro avg       0.96      0.96      0.96     20781
           weighted avg       0.96      0.96      0.96     20781

In [6]:
SVM= SVC()

In [ ]:
SVM.fit(X_train, y_train)

In [ ]:
y_pred2 = SVM.predict(X_test)

In [ ]:
accuracy2 = accuracy_score(y_test, y_pred2)

In [ ]:
report2 = classification_report(y_test, y_pred2)

In [ ]:
print("Accuracy:", accuracy2)
print("Classification Report:")
print(report2)

In [6]:
KNN=KNeighborsClassifier()

In [7]:
KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [8]:
y_pred3 = KNN.predict(X_test)

In [9]:
accuracy3 = accuracy_score(y_test, y_pred3)

In [10]:
report3 = classification_report(y_test, y_pred3)

In [11]:
print("Accuracy:", accuracy3)
print("Classification Report:")
print(report3)

Accuracy: 0.5979500505269236
Classification Report:
                         precision    recall  f1-score   support

neutral or dissatisfied       0.63      0.71      0.67     11713
              satisfied       0.55      0.45      0.50      9068

               accuracy                           0.60     20781
              macro avg       0.59      0.58      0.58     20781
           weighted avg       0.59      0.60      0.59     20781

In [6]:
# Initialize different classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier()
}

KeyError: 0

In [7]:
a=list(classifiers.keys())
print(a[0])

Random Forest

In [ ]:
# # Train and evaluate each classifier
# for name, classifier in classifiers.items():
#     classifier.fit(X_train, y_train)
#     y_pred = classifier.predict(X_test)
#     accuracy = accuracy_score(y_test, y_pred)
#     report = classification_report(y_test, y_pred)
#     print(f"===== {name} =====")
#     print("Accuracy:", accuracy)
#     print("Classification Report:")
#     print(report)
#     print("=" * 30)

===== Random Forest =====
Accuracy: 0.9621288677157018
Classification Report:
                         precision    recall  f1-score   support

neutral or dissatisfied       0.95      0.98      0.97     11713
              satisfied       0.97      0.94      0.96      9068

               accuracy                           0.96     20781
              macro avg       0.96      0.96      0.96     20781
           weighted avg       0.96      0.96      0.96     20781

==============================

In [18]:
classifier=classifiers[a[0]]
name=a[0]
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(f"===== {name} =====")
print("Accuracy:", accuracy)
print("Classification Report:")
print(report)
print("=" * 30)

===== Random Forest =====
Accuracy: 0.9639574611423897
Classification Report:
                         precision    recall  f1-score   support

neutral or dissatisfied       0.96      0.98      0.97     11713
              satisfied       0.98      0.94      0.96      9068

               accuracy                           0.96     20781
              macro avg       0.97      0.96      0.96     20781
           weighted avg       0.96      0.96      0.96     20781

==============================

In [ ]:
classifier=classifiers[a[1]]
name=a[1]
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"===== {name} =====")
print("Accuracy:", accuracy)

In [ ]:
1+1

In [ ]:
# Find the best model based on accuracy
best_model_name = max(classifiers, key=lambda k: accuracy_score(y_test, classifiers[k].predict(X_test)))
print("Best Model:", best_model_name)